apiVersion: v1
kind: Service
metadata:
  name: playground-svc
  namespace: dev
  labels:
    app: playground
spec:
  externalTrafficPolicy: Local
  ports:
  - name: http
    nodePort: 8888
    port: 8888
    protocol: TCP
    targetPort: 8888
  selector:    
    app: playground
  type: NodePort
