apiVersion: v1
kind: Service
metadata:
  name: playground
  namespace: default
  labels:
    app: playground
spec:
  externalTrafficPolicy: Local
  ports:
  - name: http
    port: 8888
    protocol: TCP
    targetPort: 8888
  selector:    
    app: playground
  type: NodePort
